### ISSUE TITLE
[Feature/Idea] Option to select which templates can be downloaded

### ISSUE THREAD

**Issue by TeYroXOfficial** [ConvoyPanel/downloader#2]
Option/flag to set what kind of operating systems we want to download.
For example:
./downloader d (to download Debian based templates)
./downloader w (to download Windows based templates)
etc...
and if no flag was set to it > ./downloader
download all templates like usual

**Comment by ericwang401** [comment]
Won't be added. Instead you can now define a link to your own JSON list of images with v2.
