### ISSUE TITLE
Cloud-init

### ISSUE THREAD

**Issue by ghost** [ConvoyPanel/downloader#7]
i think it would be amazing if Cloud-init was configured  by the script

**Comment by ericwang401** [comment]
If you can elaborate more, I could understand what exactly you want this script to do with Cloudinit. But from what I can tell, this seems outside the scope of this tool. This tool's purpose is to download and load templates into Proxmox. There's no modifications/side effects that this tool should do to the templates.

**Comment by ghost** [comment]
it should configure the cloudinit drive on eatch template, for eaze of use.

**Comment by ericwang401** [comment]
I want to clarify that the downloader tool is specifically designed to respect the original configurations set by the image creator. It downloads and loads images into Proxmox without making any modifications, ensuring the integrity of the original templates.

If Cloudinit support is needed, it should be added during the template creation process by either you or the original distributor. The downloader isn’t intended to make configuration changes, such as adding Cloudinit drives, as that would alter the template beyond its intended state.
